// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * GetConfig
       * @returns {Promise<Config>}  - Go Type: *client.Config
       */
      "GetConfig": () => {
        return window.go.main.App.GetConfig();
      },
      /**
       * GetConnected
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "GetConnected": () => {
        return window.go.main.App.GetConnected();
      },
      /**
       * GetDisplayError
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetDisplayError": () => {
        return window.go.main.App.GetDisplayError();
      },
      /**
       * GetHeartRate
       * @returns {Promise<number>}  - Go Type: int64
       */
      "GetHeartRate": () => {
        return window.go.main.App.GetHeartRate();
      },
      /**
       * GetHeartRatePercent
       * @returns {Promise<number>}  - Go Type: float64
       */
      "GetHeartRatePercent": () => {
        return window.go.main.App.GetHeartRatePercent();
      },
      /**
       * GetLoading
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "GetLoading": () => {
        return window.go.main.App.GetLoading();
      },
      /**
       * GetOS
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetOS": () => {
        return window.go.main.App.GetOS();
      },
      /**
       * SaveConfig
       * @returns {Promise<void>} 
       */
      "SaveConfig": () => {
        return window.go.main.App.SaveConfig();
      },
      /**
       * SetConnectedParameterName
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "SetConnectedParameterName": (arg1) => {
        return window.go.main.App.SetConnectedParameterName(arg1);
      },
      /**
       * SetMaxHeartRate
       * @param {number} arg1 - Go Type: int
       * @returns {Promise<void>} 
       */
      "SetMaxHeartRate": (arg1) => {
        return window.go.main.App.SetMaxHeartRate(arg1);
      },
      /**
       * SetPercentParameterName
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "SetPercentParameterName": (arg1) => {
        return window.go.main.App.SetPercentParameterName(arg1);
      },
      /**
       * SetWidgetId
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "SetWidgetId": (arg1) => {
        return window.go.main.App.SetWidgetId(arg1);
      },
    },
  },

};
export default go;
