// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * GetConnected
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "GetConnected": () => {
        return window.go.main.App.GetConnected();
      },
      /**
       * GetDisplayError
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetDisplayError": () => {
        return window.go.main.App.GetDisplayError();
      },
      /**
       * GetHeartRate
       * @returns {Promise<number>}  - Go Type: int64
       */
      "GetHeartRate": () => {
        return window.go.main.App.GetHeartRate();
      },
      /**
       * GetLoading
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "GetLoading": () => {
        return window.go.main.App.GetLoading();
      },
      /**
       * SetWidgetId
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "SetWidgetId": (arg1) => {
        return window.go.main.App.SetWidgetId(arg1);
      },
    },
  },

};
export default go;
