// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * CurrentHeartRate
       * @returns {Promise<number>}  - Go Type: int64
       */
      "CurrentHeartRate": () => {
        return window.go.main.App.CurrentHeartRate();
      },
      /**
       * GetError
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetError": () => {
        return window.go.main.App.GetError();
      },
      /**
       * IsLoading
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "IsLoading": () => {
        return window.go.main.App.IsLoading();
      },
      /**
       * SetWidgetId
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "SetWidgetId": (arg1) => {
        return window.go.main.App.SetWidgetId(arg1);
      },
      /**
       * WebSocketConnectionStatus
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "WebSocketConnectionStatus": () => {
        return window.go.main.App.WebSocketConnectionStatus();
      },
    },
  },

};
export default go;
